import type { ScholarshipScheme, SchemeCode, SchemeRuleVersion } from '@/types';

export const SCHEMES: ScholarshipScheme[] = [
  {
    code: 'PRE_MATRIC',
    name: 'Pre-Matric Scholarship for ST Students',
    shortName: 'Pre-Matric',
    targetGroup: 'School students in Class IX–X',
    description:
      'Financial assistance to ST students studying in Classes IX and X to reduce dropout rates and support completion of pre-matric education.',
    eligibility: [
      'Scheduled Tribe student',
      'Studying in Class IX or X',
      'Annual family income below ₹2.5 lakh',
      'Must be enrolled in a recognised school',
    ],
    documents: [
      'ST Certificate',
      'Income Certificate',
      'Domicile Certificate',
      'Bonafide Certificate',
      'Bank Account Proof',
    ],
    benefits: '₹1,500–₹3,500 per year (variable by category)',
    applicationPeriod: 'Jul – Oct 2026',
    stages: [
      'Application Submitted',
      'Auto-Verification',
      'School Verification',
      'State Review',
      'Sanction',
      'DBT Payment',
    ],
    incomeThreshold: 250000,
    icon: 'School',
  },
  {
    code: 'POST_MATRIC',
    name: 'Post-Matric Scholarship for ST Students',
    shortName: 'Post-Matric',
    targetGroup: 'Students pursuing recognised education after Class X',
    description:
      'Scholarship for ST students pursuing post-matriculation studies including intermediate, graduation, post-graduation, technical and professional courses.',
    eligibility: [
      'Scheduled Tribe student',
      'Completed Class X / pursuing post-matric education',
      'Annual family income below ₹2.5 lakh',
      'Enrolled in a recognised institution',
    ],
    documents: [
      'ST Certificate',
      'Income Certificate',
      'Domicile Certificate',
      'Previous Class Marksheet',
      'Bonafide Certificate',
      'Bank Account Proof',
    ],
    benefits: 'Up to ₹18,500 per year (variable by course group)',
    applicationPeriod: 'Jul – Nov 2026',
    stages: [
      'Application Submitted',
      'Auto-Verification',
      'Institution Verification',
      'State Review',
      'Sanction',
      'DBT Payment',
    ],
    incomeThreshold: 250000,
    icon: 'GraduationCap',
  },
  {
    code: 'TOP_CLASS',
    name: 'Top Class Education Scholarship for ST Students',
    shortName: 'Top Class',
    targetGroup: 'Students admitted to notified premier institutions',
    description:
      'Scholarship for ST students admitted to notified premier institutions like IITs, IIMs, AIIMS, NITs and other designated institutions.',
    eligibility: [
      'Scheduled Tribe student',
      'Admitted to a notified premier institution',
      'Annual family income below ₹6 lakh',
      'Pursuing full-time course',
    ],
    documents: [
      'ST Certificate',
      'Income Certificate',
      'Domicile Certificate',
      'Admission Letter',
      'Institution Bonafide Certificate',
      'Bank Account Proof',
    ],
    benefits: 'Full tuition + maintenance allowance up to ₹3,000/month',
    applicationPeriod: 'Aug – Dec 2026',
    stages: [
      'Application Submitted',
      'Auto-Verification',
      'Institution Verification',
      'MoTA Review',
      'Sanction',
      'DBT Payment',
    ],
    incomeThreshold: 600000,
    icon: 'Award',
  },
  {
    code: 'NFST',
    name: 'National Fellowship for Scheduled Tribe Students (NFST)',
    shortName: 'NFST',
    targetGroup: 'M.Phil. / PhD candidates',
    description:
      'Fellowship for ST students pursuing M.Phil. and PhD in recognised universities to promote higher education and research.',
    eligibility: [
      'Scheduled Tribe student',
      'Pursuing M.Phil. or PhD',
      'Qualified NET/JRF or selected through institution process',
      'Annual family income below ₹6 lakh',
    ],
    documents: [
      'ST Certificate',
      'Income Certificate',
      'NET/JRF Certificate',
      'Admission/Registration Certificate',
      'Bank Account Proof',
    ],
    benefits: 'Fellowship of ₹25,000–₹35,000/month + contingency grant',
    applicationPeriod: 'Sep – Jan 2027',
    stages: [
      'Application Submitted',
      'Auto-Verification',
      'UGC-NTA Verification',
      'MoTA Review',
      'Sanction',
      'Fellowship Disbursement',
    ],
    incomeThreshold: 600000,
    icon: 'FlaskConical',
  },
  {
    code: 'NOS',
    name: 'National Overseas Scholarship for ST Students (NOS)',
    shortName: 'NOS',
    targetGroup: 'Masters, PhD or Post-doctoral education abroad',
    description:
      'Scholarship for ST students pursuing Masters, PhD or Post-doctoral studies in foreign universities to support international education.',
    eligibility: [
      'Scheduled Tribe student',
      'Planning overseas study (Masters/PhD/Post-doc)',
      'Annual family income below ₹6 lakh',
      'Admission to a foreign university',
    ],
    documents: [
      'ST Certificate',
      'Income Certificate',
      'Domicile Certificate',
      'Foreign University Admission Letter',
      'Passport Copy',
      'Bank Account Proof',
    ],
    benefits: 'Up to $20,000 per year + tuition + maintenance',
    applicationPeriod: 'Oct 2026 – Feb 2027',
    stages: [
      'Application Submitted',
      'Auto-Verification',
      'MoTA Review',
      'Selection Committee',
      'Sanction',
      'Disbursement',
    ],
    incomeThreshold: 600000,
    icon: 'Plane',
  },
];

export function getScheme(code: SchemeCode): ScholarshipScheme | undefined {
  return SCHEMES.find((s) => s.code === code);
}

export const SCHEME_RULE_VERSIONS: SchemeRuleVersion[] = [
  {
    schemeCode: 'POST_MATRIC',
    version: 'v3.2',
    publishedDate: '01 Apr 2026',
    status: 'PUBLISHED',
    rules: [
      { label: 'Income Threshold', value: '₹2,50,000 per annum', type: 'income' },
      { label: 'Education Level', value: 'Post-Class X recognised courses', type: 'education' },
      { label: 'Institution Criteria', value: 'Recognised by UGC/AICTE/State Government', type: 'institution' },
      { label: 'Required Documents', value: 'ST, Income, Domicile, Marksheet, Bonafide, Bank', type: 'documents' },
      { label: 'Conflict Rule', value: 'Cannot hold Pre-Matric simultaneously', type: 'conflict' },
      { label: 'Application Period', value: 'Jul – Nov 2026', type: 'period' },
    ],
  },
  {
    schemeCode: 'TOP_CLASS',
    version: 'v2.1',
    publishedDate: '15 Mar 2026',
    status: 'PUBLISHED',
    rules: [
      { label: 'Income Threshold', value: '₹6,00,000 per annum', type: 'income' },
      { label: 'Education Level', value: 'Full-time UG/PG at notified institution', type: 'education' },
      { label: 'Institution Criteria', value: 'IITs, IIMs, AIIMS, NITs, notified list', type: 'institution' },
      { label: 'Required Documents', value: 'ST, Income, Admission Letter, Bonafide, Bank', type: 'documents' },
      { label: 'Conflict Rule', value: 'Cannot hold Post-Matric simultaneously', type: 'conflict' },
      { label: 'Application Period', value: 'Aug – Dec 2026', type: 'period' },
    ],
  },
  {
    schemeCode: 'PRE_MATRIC',
    version: 'v4.0',
    publishedDate: '01 Apr 2026',
    status: 'PUBLISHED',
    rules: [
      { label: 'Income Threshold', value: '₹2,50,000 per annum', type: 'income' },
      { label: 'Education Level', value: 'Class IX–X', type: 'education' },
      { label: 'Institution Criteria', value: 'Recognised school', type: 'institution' },
      { label: 'Required Documents', value: 'ST, Income, Bonafide, Bank', type: 'documents' },
      { label: 'Conflict Rule', value: 'Standalone scheme', type: 'conflict' },
      { label: 'Application Period', value: 'Jul – Oct 2026', type: 'period' },
    ],
  },
  {
    schemeCode: 'NFST',
    version: 'v2.3',
    publishedDate: '20 Mar 2026',
    status: 'PUBLISHED',
    rules: [
      { label: 'Income Threshold', value: '₹6,00,000 per annum', type: 'income' },
      { label: 'Education Level', value: 'M.Phil. / PhD', type: 'education' },
      { label: 'Institution Criteria', value: 'UGC-recognised university', type: 'institution' },
      { label: 'Required Documents', value: 'ST, Income, NET/JRF, Registration, Bank', type: 'documents' },
      { label: 'Conflict Rule', value: 'Cannot hold NOS simultaneously', type: 'conflict' },
      { label: 'Application Period', value: 'Sep – Jan 2027', type: 'period' },
    ],
  },
  {
    schemeCode: 'NOS',
    version: 'v1.8',
    publishedDate: '10 Mar 2026',
    status: 'PUBLISHED',
    rules: [
      { label: 'Income Threshold', value: '₹6,00,000 per annum', type: 'income' },
      { label: 'Education Level', value: 'Masters / PhD / Post-doc abroad', type: 'education' },
      { label: 'Institution Criteria', value: 'Foreign university (top 500 QS)', type: 'institution' },
      { label: 'Required Documents', value: 'ST, Income, Admission Letter, Passport, Bank', type: 'documents' },
      { label: 'Conflict Rule', value: 'Cannot hold NFST simultaneously', type: 'conflict' },
      { label: 'Application Period', value: 'Oct 2026 – Feb 2027', type: 'period' },
    ],
  },
];
